#!/usr/bin/env python3
"""
Single source of truth for what each section plays.

Every remote URL below came out of a Pollo generation run made in this repo's
session; the prompts and model choices are recorded in pipeline/PROMPTS.md.
Regenerate site/media/sources.js with:  python3 pipeline/make_manifest.py
"""
import json, pathlib

# tint = the render's own base colour, painted behind the <video>. If the
# network never delivers a frame the section still reads as designed instead
# of flashing a black rectangle.
CLIPS = {
    "s1-hero": {
        "tint": "linear-gradient(160deg,#FAFAFC 0%,#F1F1F6 46%,#E6E6EF 100%)",
        "tintFlat": "#F1F1F6",
        "poster":  {"local": "media/poster/s1-hero.webp",  "remote": None},
        "desktop": {"local": "media/s1-hero-1920.mp4",     "remote": None},
        "webm":    {"local": "media/s1-hero-1920.webm",    "remote": None},
        "mobile":  {"local": "media/s1-hero-mobile-1080v.mp4", "remote": None},
    },
    "s2-broken": {
        "tint": "linear-gradient(160deg,#F0F0F4 0%,#E6E6EC 52%,#DEDEE6 100%)",
        "tintFlat": "#E6E6EC",
        "poster":  {"local": "media/poster/s2-broken.webp", "remote": None},
        "desktop": {"local": "media/s2-broken-1920.mp4",    "remote": None},
        "webm":    {"local": "media/s2-broken-1920.webm",   "remote": None},
    },
    "s3-corridor": {
        "tint": "linear-gradient(180deg,#FAFAFC 0%,#F2F2F7 60%,#EAEAF1 100%)",
        "tintFlat": "#F2F2F7",
        "poster":  {"local": "media/poster/s3-corridor.webp",  "remote": None},
        "desktop": {"local": "media/s3-corridor-scrub.mp4",    "remote": None},
    },
    "s4-a": {
        "tint": "linear-gradient(160deg,#FAFAFC 0%,#EFEFF4 100%)",
        "tintFlat": "#EFEFF4",
        "poster":  {"local": "media/poster/s4-a.webp", "remote": None},
        "desktop": {"local": "media/s4-a-960.mp4",     "remote": None},
    },
    "s4-b": {
        "tint": "linear-gradient(160deg,#FAFAFC 0%,#EFEFF4 100%)",
        "tintFlat": "#EFEFF4",
        "poster":  {"local": "media/poster/s4-b.webp", "remote": None},
        "desktop": {"local": "media/s4-b-960.mp4",     "remote": None},
    },
    "s4-c": {
        "tint": "linear-gradient(160deg,#FAFAFC 0%,#EFEFF4 100%)",
        "tintFlat": "#EFEFF4",
        "poster":  {"local": "media/poster/s4-c.webp", "remote": None},
        "desktop": {"local": "media/s4-c-960.mp4",     "remote": None},
    },
    "s6-cta": {
        "tint": "linear-gradient(160deg,#FBFAF8 0%,#F3F0EA 54%,#EDE9E2 100%)",
        "tintFlat": "#F3F0EA",
        "poster":  {"local": "media/poster/s6-cta.webp", "remote": None},
        "desktop": {"local": "media/s6-cta-1920.mp4",    "remote": None},
        "webm":    {"local": "media/s6-cta-1920.webm",   "remote": None},
    },
}

# Pollo CDN URLs, filled in as each generation finishes.
REMOTE = {}   # "<clip>.<slot>" -> url

def build():
    for key, url in REMOTE.items():
        clip, slot = key.split(".", 1)
        CLIPS[clip].setdefault(slot, {"local": None})["remote"] = url
    # drop slots that ended up with nothing on either side
    out = {}
    for name, c in CLIPS.items():
        keep = {}
        for k, v in c.items():
            if isinstance(v, dict):
                if v.get("local") or v.get("remote"):
                    keep[k] = v
            else:
                keep[k] = v
        out[name] = keep
    return out

def main():
    data = build()
    js = (
        "/* GENERATED by pipeline/make_manifest.py — do not hand-edit.\n"
        " * `use` decides which column the page reads. pipeline/fetch-media.sh\n"
        " * downloads + encodes the remote column and flips this to \"local\". */\n"
        "window.CLIP_SOURCES = {\n"
        '  use: "remote",\n'
        "  clips: " + json.dumps(data, indent=2, ensure_ascii=False).replace("\n", "\n  ") + "\n"
        "};\n"
    )
    p = pathlib.Path(__file__).resolve().parent.parent / "site" / "media" / "sources.js"
    p.write_text(js, encoding="utf-8")
    have = sum(1 for c in data.values() for v in c.values()
               if isinstance(v, dict) and v.get("remote"))
    print(f"wrote {p}  ({len(data)} clips, {have} remote urls wired)")

if __name__ == "__main__":
    main()
